apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediavault-backend-deployment
  labels:
    app: mediavault-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mediavault-backend
  template:
    metadata:
      labels:
        app: mediavault-backend
    spec:
      containers:
        - name: mediavault-backend
          image: oxow/mediavault-backend:1.0.6
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: mediavault-backend-secret
                  key: JWT_SECRET
            - name: UPLOAD_DIR
              value: /tmp/uploads
          volumeMounts:
            - mountPath: /var/data
              name: mediavault-db-storage
      volumes:
        - name: mediavault-db-storage
          persistentVolumeClaim:
            claimName: mediavault-db-pvc
